In [1]:
import pandas as pd

In [2]:
df = pd.read_json('train.json')

In [3]:
df

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39774 entries, 0 to 39773
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           39774 non-null  int64
 1   cuisine      39774 non-null  object
 2   ingredients  39774 non-null  object
dtypes: int64(1), object(2)
memory usage: 932.3+ KB

In [5]:
df.shape

(39774, 3)

In [6]:
pd.read_json("train.json", typ='series')

0        {'id': 10259, 'cuisine': 'greek', 'ingredients...
1        {'id': 25693, 'cuisine': 'southern_us', 'ingre...
2        {'id': 20130, 'cuisine': 'filipino', 'ingredie...
3        {'id': 22213, 'cuisine': 'indian', 'ingredient...
4        {'id': 13162, 'cuisine': 'indian', 'ingredient...
                               ...
39769    {'id': 29109, 'cuisine': 'irish', 'ingredients...
39770    {'id': 11462, 'cuisine': 'italian', 'ingredien...
39771    {'id': 2238, 'cuisine': 'irish', 'ingredients'...
39772    {'id': 41882, 'cuisine': 'chinese', 'ingredien...
39773    {'id': 2362, 'cuisine': 'mexican', 'ingredient...
Length: 39774, dtype: object

In [7]:
pd.read_json("train.json", dtype=False)

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

# Splitting JSON Array

In [8]:
file_path = 'train.json'
with open(file_path, 'r')  as f:
    data = json.load(f)

In [9]:
print(type(data))
print(len(data))
# print(data)

<class 'list'>
39774

In [10]:
chunk_size = 8000 
for i in range(0, len(data), chunk_size):
    print(data[i])

{'id': 10259, 'cuisine': 'greek', 'ingredients': ['romaine lettuce', 'black olives', 'grape tomatoes', 'garlic', 'pepper', 'purple onion', 'seasoning', 'garbanzo beans', 'feta cheese crumbles']}
{'id': 42129, 'cuisine': 'indian', 'ingredients': ['daikon', 'cumin', 'chaat masala', 'lime juice']}
{'id': 3771, 'cuisine': 'cajun_creole', 'ingredients': ['small red beans', 'bacon', 'purple onion', 'cooked rice', 'Sriracha', 'garlic', 'smoked ham hocks', 'pepper', 'stout', 'salt', 'chicken broth', 'olive oil', 'brats', 'green pepper']}
{'id': 26610, 'cuisine': 'italian', 'ingredients': ['fresh basil', 'olive oil', 'salt', 'pitted black olives', 'dry white wine', 'chicken thighs', 'canned low sodium chicken broth', 'ground black pepper', 'onions', 'fresh rosemary', 'crushed tomatoes', 'garlic', 'dried rosemary']}
{'id': 531, 'cuisine': 'mexican', 'ingredients': ['white onion', 'serrano chile', 'fresh lime juice', 'kosher salt', 'tomatoes', 'chopped cilantro fresh']}

In [11]:
for i in range(0, len(data), chunk_size):    
    chunk = data[i:i + chunk_size]
    df = pd.DataFrame(chunk)
    print(df.shape)

(8000, 3)
(8000, 3)
(8000, 3)
(8000, 3)
(7774, 3)

# Work with SQL Data

In [12]:
!pip install mysql

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: mysql in C:\Users\sathv\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (0.0.3)
Requirement already satisfied: mysqlclient in C:\Users\sathv\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from mysql) (2.2.8)

In [13]:
!pip install --upgrade pip

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pip in C:\Users\sathv\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (26.0.1)

In [14]:
# Check file location

import sys
print(sys.executable)

C:\Users\sathv\anaconda3\python.exe

In [15]:
# Doanload mysql connector module

!pip install mysql-connector-python

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: mysql-connector-python in C:\Users\sathv\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (9.4.0)

In [16]:
!{sys.executable} -m pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in c:\users\sathv\anaconda3\lib\site-packages (9.6.0)

In [17]:
import mysql.connector

In [21]:
conn = mysql.connector.connect(host="localhost", user="root", password="", database="world")
print("Connected!")

Connected!

In [22]:
pd.read_sql_query("SELECT *from city", conn)

C:\Users\sathv\AppData\Local\Temp\ipykernel_39612\2606386377.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT *from city", conn)

        ID            Name CountryCode       District  Population
0        1           Kabul         AFG          Kabol     1780000
1        2        Qandahar         AFG       Qandahar      237500
2        3           Herat         AFG          Herat      186800
3        4  Mazar-e-Sharif         AFG          Balkh      127800
4        5       Amsterdam         NLD  Noord-Holland      731200
...    ...             ...         ...            ...         ...
4074  4075      Khan Yunis         PSE     Khan Yunis      123175
4075  4076          Hebron         PSE         Hebron      119401
4076  4077        Jabaliya         PSE     North Gaza      113901
4077  4078          Nablus         PSE         Nablus      100231
4078  4079           Rafah         PSE          Rafah       92020

[4079 rows x 5 columns]

In [31]:
!pip install pymysql

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pymysql in C:\Users\sathv\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (1.1.2)

In [36]:
print(sys.executable)

C:\Users\sathv\anaconda3\python.exe

In [37]:
import pymysql

In [47]:
# USe SQLAlchemy for production

from sqlalchemy import create_engine

engine = create_engine("mysql+pymysql://root:@localhost:3306/world")

try:
    connection = engine.connect()
    print("Connection established successfully!")
    connection.close()
except Exception as e:
    print(f"Error connecting to the database: {e}")
    
df = pd.read_sql_query("SELECT * FROM city", engine, index_col="ID")
print(df)

Connection established successfully!
                Name CountryCode       District  Population
ID
1              Kabul         AFG          Kabol     1780000
2           Qandahar         AFG       Qandahar      237500
3              Herat         AFG          Herat      186800
4     Mazar-e-Sharif         AFG          Balkh      127800
5          Amsterdam         NLD  Noord-Holland      731200
...              ...         ...            ...         ...
4075      Khan Yunis         PSE     Khan Yunis      123175
4076          Hebron         PSE         Hebron      119401
4077        Jabaliya         PSE     North Gaza      113901
4078          Nablus         PSE         Nablus      100231
4079           Rafah         PSE          Rafah       92020

[4079 rows x 4 columns]

In [44]:
df.shape

(4079, 5)

In [45]:
df.columns

Index(['ID', 'Name', 'CountryCode', 'District', 'Population'], dtype='object')