In [2]:
import pandas as pd
import requests

In [64]:
res = requests.get("https://api.themoviedb.org/3/movie/top_rated?api_key=9c52ef5a134d2273347f9db339317aae&language=en-US&page=1&region=AT")

In [65]:
pd.DataFrame(res.json()['results']).head(3)[['id','title','overview','release_date','vote_average']]

,id,title,overview,release_date,vote_average
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,8.700
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,8.686
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,8.571

In [40]:
df = pd.DataFrame()

In [47]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
pages = res.json()['total_pages']
pages

In [67]:
for i in range(1, 500):
    res = requests.get("https://api.themoviedb.org/3/movie/top_rated?api_key=9c52ef5a134d2273347f9db339317aae&language=en-US&page={}&region=AT".format(i))
    temp_df = pd.DataFrame(res.json()['results'])[['id','title','overview','release_date','vote_average']]
    df = pd.concat([df, temp_df], ignore_index=True)

In [69]:
df

,id,title,overview,release_date,vote_average
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,8.700
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,8.686
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,8.571
3,424,Schindler's List,The true story of how businessman Oskar Schind...,1994-03-04,8.567
4,389,12 Angry Men,The defense and the prosecution have rested an...,1957-12-20,8.559
...,...,...,...,...,...
29995,420245,Don't Knock Twice,A mother desperate to reconnect with her troub...,2017-01-12,5.512
29996,89008,The Oranges,A man's affair with his friend's much-younger ...,2011-09-09,5.511
29997,16258,The Butterfly Effect 3: Revelations,The story revolves around a man trying to unco...,2009-01-09,5.513
29998,190847,The Last Days on Mars,On the last day of the first manned mission to...,2013-08-11,5.510
29999,1161048,The Conference,A ragtag group of public sector employees batt...,2023-10-13,5.509

In [70]:
df.to_csv("30000_movie_collection.csv")

In [71]:
df

,id,title,overview,release_date,vote_average
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,8.700
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,8.686
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,8.571
3,424,Schindler's List,The true story of how businessman Oskar Schind...,1994-03-04,8.567
4,389,12 Angry Men,The defense and the prosecution have rested an...,1957-12-20,8.559
...,...,...,...,...,...
29995,420245,Don't Knock Twice,A mother desperate to reconnect with her troub...,2017-01-12,5.512
29996,89008,The Oranges,A man's affair with his friend's much-younger ...,2011-09-09,5.511
29997,16258,The Butterfly Effect 3: Revelations,The story revolves around a man trying to unco...,2009-01-09,5.513
29998,190847,The Last Days on Mars,On the last day of the first manned mission to...,2013-08-11,5.510
29999,1161048,The Conference,A ragtag group of public sector employees batt...,2023-10-13,5.509

In [72]:
import pandas as pd

a = pd.DataFrame({"a":[1,2], "b":[3,4]})
b = pd.DataFrame({"a":[5,6], "b":[7,8]})

res = pd.concat([a, b], ignore_index=True)
print(res)

   a  b
0  1  3
1  2  4
2  5  7
3  6  8