In [2]:
import pandas as pd

In [64]:
df = pd.read_csv("Countries.csv", index_col="country", usecols=['country','capital_city','region'])

In [65]:
df.shape

(194, 2)

In [66]:
for chunk in pd.read_csv("Countries.csv", chunksize=50):
    print(chunk.shape)
    chunk.to_csv('chunk_country.csv', index=False, mode='a', header=False)

(50, 64)
(50, 64)
(50, 64)
(44, 64)

In [23]:
df.head()

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
0,Afghanistan,Islamic State of Afghanistan,Afghan afghani,Kabul,Southern Asia,Asia,Afghan,33.0,65.0,383560.0,...,41128771,27.01610,30181937,10946834,2.14,2.97,Authoritarian,12.9,Ashraf Ghani,President
1,Albania,Republic of Albania,Albanian lek,Tirana,Southern Europe,Europe,Albanian,41.0,20.0,11655.5,...,2775634,35.71430,1004807,1770827,2.62,5.98,Hybrid regime,33.7,Edi Rama,Prime Minister
2,Algeria,People's Democratic Republic of Algeria,Algerian dinar,Algiers,Northern Africa,Africa,Algerian,28.0,3.0,413588.0,...,44903225,8.10811,11328186,33575039,1.71,3.50,Authoritarian,24.0,Abdelmadjid Tebboune,President
3,Andorra,Principality of Andorra,Euro,Andorra la Vella,Southern Europe,Europe,Andorran,42.5,1.5,187.2,...,79824,46.42860,9730,70094,3.17,0.00,Unknown,38.9,Xavier Espot Zamora,Head of Government
4,Angola,People's Republic of Angola,Angolan kwanza,Luanda,Middle Africa,Africa,Angolan,-12.5,18.5,569525.0,...,35588987,33.63640,11359649,24229338,2.24,3.62,Authoritarian,12.4,João Lourenço,President

In [29]:
import requests
from io import StringIO

url = "https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv"
headers = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"}
req = requests.get(url, headers=headers)
data = StringIO(req.text)

df = pd.read_csv(data)
df.columns

Index(['Country', 'Region'], dtype='object')

In [33]:
df

       Country         Region
0      Algeria         AFRICA
1       Angola         AFRICA
2        Benin         AFRICA
3     Botswana         AFRICA
4      Burkina         AFRICA
..         ...            ...
189   Paraguay  SOUTH AMERICA
190       Peru  SOUTH AMERICA
191   Suriname  SOUTH AMERICA
192    Uruguay  SOUTH AMERICA
193  Venezuela  SOUTH AMERICA

[194 rows x 2 columns]

In [61]:
df = pd.read_csv("Countries.csv", skiprows=[0,1], header=1)
df.head()

,Algeria,People's Democratic Republic of Algeria,Algerian dinar,Algiers,Northern Africa,Africa,Algerian,28.0,3.0,413588.0,...,44903225,8.10811,11328186,33575039,1.71,3.5,Authoritarian,24.0,Abdelmadjid Tebboune,President
0,Andorra,Principality of Andorra,Euro,Andorra la Vella,Southern Europe,Europe,Andorran,42.50,1.5,187.2,...,79824,46.4286,9730,70094,3.17,0.00,Unknown,38.9,Xavier Espot Zamora,Head of Government
1,Angola,People's Republic of Angola,Angolan kwanza,Luanda,Middle Africa,Africa,Angolan,-12.50,18.5,569525.0,...,35588987,33.6364,11359649,24229338,2.24,3.62,Authoritarian,12.4,João Lourenço,President
2,Antigua and Barbuda,Antigua and Barbuda,East Caribbean dollar,Saint John's,Caribbean,Americas,Antiguan,17.05,-61.8,90.0,...,93763,11.1111,70935,22828,0.00,0.00,Unknown,31.1,Gaston Browne,Prime Minister
3,Argentina,Argentine Republic,Argentine peso,Buenos Aires,South America,Americas,Argentine,-34.00,-64.0,1083820.0,...,46234830,44.7471,3538352,42696478,2.76,7.02,Flawed democracy,27.6,Alberto Fernández,President
4,Armenia,Republic of Armenia,Armenian dram,Yerevan,Western Asia,Asia,Armenian,40.00,45.0,16760.0,...,2780469,35.5140,1012841,1767628,2.70,4.79,Hybrid regime,30.8,Nikol Pashinyan,Prime Minister

In [58]:
def rename(name):
    if name == 'Islamic State of Afghanistan':
        return "ISA"
    else:
        return name
print(rename('Islamic State of Afghanistan'))

ISA

In [59]:
df = pd.read_csv("Countries.csv", converters={'country_long':rename})

In [60]:
df.head()

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
0,Afghanistan,ISA,Afghan afghani,Kabul,Southern Asia,Asia,Afghan,33.0,65.0,383560.0,...,41128771,27.01610,30181937,10946834,2.14,2.97,Authoritarian,12.9,Ashraf Ghani,President
1,Albania,Republic of Albania,Albanian lek,Tirana,Southern Europe,Europe,Albanian,41.0,20.0,11655.5,...,2775634,35.71430,1004807,1770827,2.62,5.98,Hybrid regime,33.7,Edi Rama,Prime Minister
2,Algeria,People's Democratic Republic of Algeria,Algerian dinar,Algiers,Northern Africa,Africa,Algerian,28.0,3.0,413588.0,...,44903225,8.10811,11328186,33575039,1.71,3.50,Authoritarian,24.0,Abdelmadjid Tebboune,President
3,Andorra,Principality of Andorra,Euro,Andorra la Vella,Southern Europe,Europe,Andorran,42.5,1.5,187.2,...,79824,46.42860,9730,70094,3.17,0.00,Unknown,38.9,Xavier Espot Zamora,Head of Government
4,Angola,People's Republic of Angola,Angolan kwanza,Luanda,Middle Africa,Africa,Angolan,-12.5,18.5,569525.0,...,35588987,33.63640,11359649,24229338,2.24,3.62,Authoritarian,12.4,João Lourenço,President